[versions]
aboutlib_version = "10.10.0"
# AM (REMOVE_ACRA_FIREBASE) -->
# acra = "5.11.3"
# <-- AM (REMOVE_ACRA_FIREBASE)
# AM (REMOVE_LIBRARIES) -->
# leakcanary = "2.13"
# <-- AM (REMOVE_LIBRARIES)
moko = "0.23.0"
okhttp_version = "5.0.0-alpha.12"
richtext = "0.20.0"
shizuku_version = "12.2.0"
sqldelight = "2.0.0"
sqlite = "2.4.0"
voyager = "1.0.0"
tvMaterialVersion = "1.0.0"

[libraries]
desugar = "com.android.tools:desugar_jdk_libs:2.1.2"
android-shortcut-gradle = "com.github.zellius:android-shortcut-gradle-plugin:0.1.2"

rxjava = "io.reactivex:rxjava:1.3.8"

okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp_version" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp_version" }
okhttp-brotli = { module = "com.squareup.okhttp3:okhttp-brotli", version.ref = "okhttp_version" }
okhttp-dnsoverhttps = { module = "com.squareup.okhttp3:okhttp-dnsoverhttps", version.ref = "okhttp_version" }
okio = "com.squareup.okio:okio:3.7.0"

conscrypt-android = "org.conscrypt:conscrypt-android:2.5.2"

quickjs-android = "app.cash.quickjs:quickjs-android:0.9.2"

jsoup = "org.jsoup:jsoup:1.17.2"

disklrucache = "com.jakewharton:disklrucache:2.0.2"
unifile = "com.github.tachiyomiorg:unifile:7c257e1c64"
junrar = "com.github.junrar:junrar:7.5.5"

sqlite-framework = { module = "androidx.sqlite:sqlite-framework", version.ref = "sqlite" }
sqlite-ktx = { module = "androidx.sqlite:sqlite-ktx", version.ref = "sqlite" }
sqlite-android = "com.github.requery:sqlite-android:3.43.0"

preferencektx = "androidx.preference:preference-ktx:1.2.1"

injekt-core = "com.github.inorichi.injekt:injekt-core:65b0440"

coil-bom = { module = "io.coil-kt:coil-bom", version = "2.5.0" }
coil-core = { module = "io.coil-kt:coil" }
coil-gif = { module = "io.coil-kt:coil-gif" }
coil-compose = { module = "io.coil-kt:coil-compose" }

subsamplingscaleimageview = "com.github.tachiyomiorg:subsampling-scale-image-view:aeaa170036"
# AM (REMOVE_LIBRARIES) -->
# image-decoder = "com.github.tachiyomiorg:image-decoder:e08e9be535"
# <-- AM (REMOVE_LIBRARIES)

natural-comparator = "com.github.gpanther:java-nat-sort:natural-comparator-1.1"

richtext-commonmark = { module = "com.halilibo.compose-richtext:richtext-commonmark", version.ref = "richtext" }
richtext-m3 = { module = "com.halilibo.compose-richtext:richtext-ui-material3", version.ref = "richtext" }

material = "com.google.android.material:material:1.12.0"
flexible-adapter-core = "com.github.arkon.FlexibleAdapter:flexible-adapter:c8013533"
# AM (REMOVE_LIBRARIES) -->
# photoview = "com.github.chrisbanes:PhotoView:2.3.0"
# directionalviewpager = "com.github.tachiyomiorg:DirectionalViewPager:1.0.0"
# insetter = "dev.chrisbanes.insetter:insetter:0.6.1"
# <-- AM (REMOVE_LIBRARIES)
compose-materialmotion = "io.github.fornewid:material-motion-compose-core:1.1.0"

swipe = "me.saket.swipe:swipe:1.2.0"

moko-core = { module = "dev.icerock.moko:resources", version.ref = "moko" }
moko-gradle = { module = "dev.icerock.moko:resources-generator", version.ref = "moko" }

logcat = "com.squareup.logcat:logcat:0.1"

# AM (REMOVE_ACRA_FIREBASE) -->
# acra-http = { module = "ch.acra:acra-http", version.ref = "acra" }
# acra-scheduler = { module = "ch.acra:acra-advanced-scheduler", version.ref = "acra" }
# <-- AM (REMOVE_ACRA_FIREBASE)

# AM (REMOVE_LIBRARIES) -->
# aboutLibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutlib_version" }
# <-- AM (REMOVE_LIBRARIES)
aboutLibraries-gradle = { module = "com.mikepenz.aboutlibraries.plugin:aboutlibraries-plugin", version.ref = "aboutlib_version" }
aboutLibraries-compose = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutlib_version" }

shizuku-api = { module = "dev.rikka.shizuku:api", version.ref = "shizuku_version" }
shizuku-provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizuku_version" }

# AM (REMOVE_LIBRARIES) -->
# leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
# leakcanary-plumber = { module = "com.squareup.leakcanary:plumber-android", version.ref = "leakcanary" }
# <-- AM (REMOVE_LIBRARIES)

sqldelight-android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions-jvm", version.ref = "sqldelight" }
sqldelight-android-paging = { module = "app.cash.sqldelight:androidx-paging3-extensions", version.ref = "sqldelight" }
sqldelight-dialects-sql = { module = "app.cash.sqldelight:sqlite-3-38-dialect", version.ref = "sqldelight" }
sqldelight-gradle = { module = "app.cash.sqldelight:gradle-plugin", version.ref = "sqldelight" }

junit = "org.junit.jupiter:junit-jupiter:5.10.1"
kotest-assertions = "io.kotest:kotest-assertions-core:5.8.0"
mockk = "io.mockk:mockk:1.13.9"

voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-screenmodel = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyager" }
voyager-tab-navigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }
# AM (REMOVE_LIBRARIES) -->
# voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
# <-- AM (REMOVE_LIBRARIES)

ktlint = "org.jlleitschuh.gradle:ktlint-gradle:12.0.3"

aniyomi-mpv = "com.github.aniyomiorg:aniyomi-mpv-lib:1.15.n"
ffmpeg-kit = "com.github.jmir1:ffmpeg-kit:1.15"
arthenica-smartexceptions = "com.arthenica:smart-exception-java:0.2.1"

seeker = "io.github.2307vivek:seeker:1.1.1"

truetypeparser = "io.github.yubyf:truetypeparser-light:2.1.4"

# AM (SYNC_DRIVE) -->
google-api-services-drive = "com.google.apis:google-api-services-drive:v3-rev197-1.25.0"
google-api-client-oauth = "com.google.oauth-client:google-oauth-client:1.34.1"
tv-material = { group = "androidx.tv", name = "tv-material", version.ref = "tvMaterialVersion" }
# <-- AM (SYNC_DRIVE)

[bundles]
# AM (REMOVE_ACRA_FIREBASE) -->
# acra = ["acra-http", "acra-scheduler"]
# <-- AM (REMOVE_ACRA_FIREBASE)
okhttp = ["okhttp-core", "okhttp-logging", "okhttp-brotli", "okhttp-dnsoverhttps"]
js-engine = ["quickjs-android"]
sqlite = ["sqlite-framework", "sqlite-ktx", "sqlite-android"]
coil = ["coil-core", "coil-gif", "coil-compose"]
shizuku = ["shizuku-api", "shizuku-provider"]
sqldelight = ["sqldelight-android-driver", "sqldelight-coroutines", "sqldelight-android-paging"]
# AM (REMOVE_LIBRARIES) -->
voyager = ["voyager-navigator", "voyager-screenmodel", "voyager-tab-navigator"]
# <-- AM (REMOVE_LIBRARIES)
richtext = ["richtext-commonmark", "richtext-m3"]
test = ["junit", "kotest-assertions", "mockk"]
